module.exports = {
  // Modulo que exporta toda la base de datos de los elementos
  
  
    elements: [
      {
        nombre: 'Null',
        suma: 'Lugar 0'
      , color: ""},
      {
        nombre: 'Hidrogeno',
        masaAtomica: 1.008,
        categoria: 'Halogenos',
        numeroAtomico: 1,
        periodo: 1,
        noOxidacion: "+1, -1",
        electronegatividad:  2.20,
        impactoEconomico: "El hidrógeno es utilizado en la producción de amoníaco y en la refinación de petróleo y gas natural. También se está investigando como posible fuente de energía limpia.",
        impactoAmbiental: "El hidrógeno no es tóxico ni contaminante, pero su producción a partir de combustibles fósiles todavía produce emisiones de gases de efecto invernadero.",
        phase: 'Gas',
        simbolo: 'H',
        xpos: 1,
        ypos: 1,
        shells: [1],
         urlNatural: "/images/natural/1.png",
           urlUtilidad: "/images/utilidad/1.png"
      , color: "#39a576"},
      {
        nombre: 'Helio',
        masaAtomica: 4.0026022,
        categoria: 'Gas noble',
        numeroAtomico: 2,
        periodo: 1,
        noOxidacion: "0",
        electronegatividad:  "Desconocido",
        impactoEconomico: "El helio es utilizado en la industria de la refrigeración y en la producción de equipos de soldadura. También se utiliza en aplicaciones de investigación y tecnológicas, como en la detección de fugas y la producción de láseres.",
        impactoAmbiental: "El helio es un gas inerte que no reacciona con otros elementos, por lo que no tiene un impacto ambiental significativo.",
        phase: 'Gas',
        simbolo: 'He',
        xpos: 18,
        ypos: 1,
        shells: [2],
         urlNatural: "/images/natural/2.png",
           urlUtilidad: "/images/utilidad/2.png"
      , color: "#e40c9c"},
      {
        nombre: 'Litio',
        masaAtomica: 6.94,
        categoria: 'Metales Alcalinos', 
        numeroAtomico: 3,
        periodo: 2,
        noOxidacion: "1+",
        electronegatividad:  0.98 ,
        impactoEconomico: "El litio es utilizado en la producción de baterías recargables, aleaciones metálicas y en medicamentos psiquiátricos.",
        impactoAmbiental: "La minería del litio puede tener impactos ambientales significativos, como la contaminación del agua y la pérdida de hábitats de vida silvestre.",
        phase: 'Solid',
        simbolo: 'Li',
        xpos: 1,
        ypos: 2,
        shells: [2, 1],
         urlNatural: "/images/natural/3.png",
           urlUtilidad: "/images/utilidad/3.png"
      , color: "#eb5d0b"},
      {
        nombre: 'Berilio',
        masaAtomica: 9.01218315,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 4,
        periodo: 2,
        noOxidacion: "2+",
        electronegatividad:  1.57,
        impactoEconomico: "El berilio se utiliza en la producción de aleaciones metálicas para la industria aeroespacial y de defensa, así como en equipos electrónicos y médicos.",
        impactoAmbiental: "La exposición al polvo de berilio puede causar enfermedades pulmonares y otros efectos adversos en la salud. La minería del berilio también puede tener impactos ambientales negativos.",
        simbolo: 'Be',
        xpos: 2,
        ypos: 2,
        shells: [2, 2],
         urlNatural: "/images/natural/4.png",
           urlUtilidad: "/images/utilidad/4.png"
      , color: "#e2b00a"},
      {
        nombre: 'Boro',
        masaAtomica: 10.81,
        categoria: 'Metaloides',
        numeroAtomico: 5,
        periodo: 2,
        noOxidacion: "+3",
        electronegatividad:  2.20,
        impactoEconomico: "El boro se utiliza en la producción de vidrio resistente al calor, fibras textiles y productos químicos. También se utiliza en aleaciones y en la industria aeroespacial.",
        impactoAmbiental: "d",
        simbolo: 'B',
        xpos: 13,
        ypos: 2,
        shells: [2, 3],
         urlNatural: "/images/natural/5.png",
           urlUtilidad: "/images/utilidad/5.png"
      , color: "#15864e"},
      {
        nombre: 'Carbono',
        masaAtomica: 12.011,
        categoria: 'Otros no metales',
        numeroAtomico: 6,
        periodoo: 2,
        noOxidacion: "-4, +4",
        electronegatividad: 2.55,
        impactoEconomico: "Alto",
        impactoAmbiental: "Medio",
        simbolo: 'C',
        xpos: 14,
        ypos: 2,
        shells: [2, 4],
         urlNatural: "/images/natural/6.png",
           urlUtilidad: "/images/utilidad/6.png"
      , color: "#148088"},
      {
        nombre: 'Nitrogeno',
        masaAtomica: 14.007,
        boil: 77.355,
        categoria: 'Otros no metales',
        numeroAtomico: 7,
        periodoo: 2,
        noOxidacion: "-3, -2, -1, +1, +2, +3, +4, +5",
        electronegatividad: 3.04,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'N',
        xpos: 15,
        ypos: 2,
        shells: [2, 5],
         urlNatural: "/images/natural/7.png",
           urlUtilidad: "/images/utilidad/7.png"
      , color: "#148088"},
      {
        nombre: 'Oxigeno',
        masaAtomica: 15.999,
        categoria: 'Otros no metales',
        numeroAtomico: 8,
        periodoo: 2,
        noOxidacion: "-2",
        electronegatividad: 3.44,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'O',
        xpos: 16,
        ypos: 2,
        shells: [2, 6],
         urlNatural: "/images/natural/8.png",
           urlUtilidad: "/images/utilidad/8.png"
      , color: "#148088"},
      {
        nombre: 'Fluor',
        masaAtomica: 18.9984031636,
        categoria: 'Halogenos',
        numeroAtomico: 9,
        periodoo: 2,
        noOxidacion: "-1",
        electronegatividad: 3.98,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'F',
        xpos: 17,
        ypos: 2,
        shells: [2, 7],
         urlNatural: "/images/natural/9.png",
           urlUtilidad: "/images/utilidad/9.png"
      , color: "#39a576"},
      {
        nombre: 'Neon',
        masaAtomica: 20.17976,
        categoria: 'Gas noble',
        numeroAtomico: 10,
        periodoo: 2,
        noOxidacion: "0",
        electronegatividad: null,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Nulo",
        simbolo: 'Ne',
        xpos: 18, 
        ypos: 2,
        shells: [2, 8],
         urlNatural: "/images/natural/10.png",
           urlUtilidad: "/images/utilidad/10.png"
      , color: "#e40c9c"},
      {
        nombre: 'Sodio',
        masaAtomica: 22.989769282,
        categoria: 'Metales Alcalinos',
        numeroAtomico: 11,
        periodoo: 3,
        noOxidacion: "+1",
        electronegatividad: 0.93,
        impactoEconomico: "Alto",
        impactoAmbiental: "Medio",
        simbolo: 'Na',
        xpos: 1,
        ypos: 3,
        shells: [2, 8, 1],
         urlNatural: "/images/natural/11.png",
           urlUtilidad: "/images/utilidad/11.png"
      , color: "#eb5d0b"},
      {
        nombre: 'Magnesio',
        masaAtomica: 24.305,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 12,
        periodoo: 3,
        noOxidacion: "+2",
        electronegatividad: 1.31,
        impactoEconomico: "Medio",
        impactoAmbiental: "Medio"
    ,
        simbolo: 'Mg',
        xpos: 2,
        ypos: 3,
        shells: [2, 8, 2],
         urlNatural: "/images/natural/12.png",
           urlUtilidad: "/images/utilidad/12.png"
      , color: "#e2b00a"},
      {
        nombre: 'Aluminio',
        masaAtomica: 26.98153857,
        categoria: 'Otro metal',
        numeroAtomico: 13,
        numeroAtomico: 13,
        periodoo: 3,
        noOxidacion: "+3",
        electronegatividad: 1.61,
        impactoEconomico: "Alto",
        impactoAmbiental: "Alto",
        periodo: 3,
        simbolo: 'Al',
        xpos: 13,
        ypos: 3,
        shells: [2, 8, 3],
         urlNatural: "/images/natural/13.png",
           urlUtilidad: "/images/utilidad/13.png"
      , color: "#0960e4"},
      {
        nombre: 'Silicio',
        masaAtomica: 28.085,
        categoria: 'Metaloides',
        numeroAtomico: 14,
        periodoo: 3,
        noOxidacion: "-4, +2, +4",
        electronegatividad: 1.9,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        periodo: 3,
        simbolo: 'Si',
        xpos: 14,
        ypos: 3,
        shells: [2, 8, 4],
         urlNatural: "/images/natural/14.png",
           urlUtilidad: "/images/utilidad/14.png"
      , color: "#15864e"},
      {
        nombre: 'Fosforo',
        masaAtomica: 30.9737619985,  
        categoria: 'Otros no metales',
        numeroAtomico: 15,
        periodoo: 3,
        noOxidacion: "-3, -2, -1, +1, +2, +3, +4, +5",
        electronegatividad: 2.19,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        periodo: 3,
        simbolo: 'P',
        xpos: 15,
        ypos: 3,
        shells: [2, 8, 5],
         urlNatural: "/images/natural/15.png",
           urlUtilidad: "/images/utilidad/15.png"
      , color: ""},
      {
        nombre: 'Azufre',
        masaAtomica: 32.06,
        categoria: 'Otros no metales',
        numeroAtomico: 16,
        periodoo: 3,
        noOxidacion: "-2, +2, +4, +6",
        electronegatividad: 2.58,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'S',
        xpos: 16,
        ypos: 3,
        shells: [2, 8, 6],
         urlNatural: "/images/natural/16.png",
           urlUtilidad: "/images/utilidad/16.png"
      , color: "#148088"},
      {
        nombre: 'Cloro',
        masaAtomica: 35.45,
        categoria: 'Halogenos',
          numeroAtomico: 17,
        periodoo: 3,
        noOxidacion: "-1, +1, +3, +5, +7",
        electronegatividad: 3.16,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'Cl',
        xpos: 17,
        ypos: 3,
        shells: [2, 8, 7],
         urlNatural: "/images/natural/17.png",
           urlUtilidad: "/images/utilidad/17.png"
      , color: "#39a576"},
      {
        nombre: 'Argon',
        masaAtomica: 39.9481,
        categoria: 'Gas noble',
        numeroAtomico: 18,
    periodoo: 3,
    noOxidacion: "0",
    electronegatividad: null,
    impactoEconomico: "Bajo",
    impactoAmbiental: "Nulo",
        simbolo: 'Ar',
        xpos: 18,
        ypos: 3,
        shells: [2, 8, 8],
         urlNatural: "/images/natural/18.png",
           urlUtilidad: "/images/utilidad/18.png"
      , color: "#e40c9c"},
      {
        nombre: 'Potasio',
        masaAtomica: 39.09831,
        categoria: 'Metales Alcalinos',
        numeroAtomico: 19,
        periodoo: 4,
        noOxidacion: "+1",
        electronegatividad: 0.82,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Medio",
        simbolo: 'K',
        xpos: 1,
        ypos: 4,
        shells: [2, 8, 8, 1],
         urlNatural: "/images/natural/19.png",
           urlUtilidad: "/images/utilidad/19.png"
      , color: "#eb5d0b"},
      {
        nombre: 'Calcio',
        masaAtomica: 40.0784,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 20,
        periodoo: 4,
        noOxidacion: "+2",
        electronegatividad: 1,
        impactoEconomico: "Alto",
        impactoAmbiental: "Medio",
        simbolo: 'Ca',
        xpos: 2,
        ypos: 4,
        shells: [2, 8, 8, 2],
         urlNatural: "/images/natural/20.png",
           urlUtilidad: "/images/utilidad/20.png"
      , color: "#e2b00a"},
      {
        nombre: 'Escandio',
        masaAtomica: 44.9559085,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 21,
        periodoo: 4,
        noOxidacion: "+1, +2, +3",
        electronegatividad: 1.36,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'Sc',
        xpos: 3,
        ypos: 4,
        shells: [2, 8, 9, 2],
         urlNatural: "/images/natural/21.png",
           urlUtilidad: "/images/utilidad/21.png"
      , color: "#e9ff08"},
      {
        nombre: 'Titanio',
        masaAtomica: 47.8671,
        categoria: 'Metales alcalinoterreos',
       nombre: "Titanio",
    masaAtomica: 47.87,
    numeroAtomico: 22,
    periodoo: 4,
    noOxidacion: "+2, +3, +4",
    electronegatividad: 1.54,
    impactoEconomico: "Alto",
    impactoAmbiental: "Medio",
        simbolo: 'Ti',
        xpos: 4,
        ypos: 4,
        shells: [2, 8, 10, 2],
         urlNatural: "/images/natural/22.png",
           urlUtilidad: "/images/utilidad/22.png",
         urlNatural: "#e9ff08"
      , color: "#e9ff08"},
      {
        nombre: 'Vanadio',
        masaAtomica: 50.94151,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 23,
        periodoo: 4,
        noOxidacion: "+2, +3, +4, +5",
        electronegatividad: 1.63,
        impactoEconomico: "Medio",
        impactoAmbiental: "Alto",
        simbolo: 'V',
        xpos: 5,
        ypos: 4,
        shells: [2, 8, 11, 2],
         urlNatural: "/images/natural/23.png",
           urlUtilidad: "/images/utilidad/23.png"
      , color: "#e9ff08"},
      {
        nombre: 'Cromo',
        masaAtomica: 51.99616,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 24,
        periodoo: 4,
        noOxidacion: "+2, +3, +6",
        electronegatividad: 1.66,
        impactoEconomico: "Alto",
        impactoAmbiental: "Alto",
        simbolo: 'Cr',
        xpos: 6,
        ypos: 4,
        shells: [2, 8, 13, 1],
         urlNatural: "/images/natural/24.png",
           urlUtilidad: "/images/utilidad/24.png"
      , color: "#e9ff08"},
      {
        nombre: 'Manganeso',
        masaAtomica: 54.9380443,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 25,
        periodoo: 4,
        noOxidacion: "+2, +3, +4, +6, +7",
        electronegatividad: 1.55,
        impactoEconomico: "Alto",
        impactoAmbiental: "Alto",
        simbolo: 'Mn',
        xpos: 7,
        ypos: 4,
        shells: [2, 8, 13, 2],
         urlNatural: "/images/natural/25.png",
           urlUtilidad: "/images/utilidad/25.png",
     color: "#e9ff08"},
      {
        nombre: 'Hierro',
        masaAtomica: 55.8452,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 26,
    periodoo: 4,
    noOxidacion: "+2, +3",
    electronegatividad: 1.83,
    impactoEconomico: "Alto",
    impactoAmbiental: "Alto",
        simbolo: 'Fe',
        xpos: 8,
        ypos: 4,
        shells: [2, 8, 14, 2],
         urlNatural: "/images/natural/26.png",
           urlUtilidad: "/images/utilidad/26.png",
    color: "#e9ff08"},
      {
        nombre: 'Cobalto',
        masaAtomica: 58.9331944,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 27,
        periodoo: 4,
        noOxidacion: "+2, +3",
        electronegatividad: 1.88,
        impactoEconomico: "Medio",
        impactoAmbiental: "Alto",
        simbolo: 'Co',
        xpos: 9,
        ypos: 4,
        shells: [2, 8, 15, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Niquel',
        categoria: 'Metales alcalinoterreos',
        masaAtomica: 58.69344,
        numeroAtomico: 28,
        periodoo: 4,
        noOxidacion: "+2, +3",
        electronegatividad: 1.91,
        impactoEconomico: "Alto",
        impactoAmbiental: "Medio",
        simbolo: 'Ni',
        xpos: 10,
        ypos: 4,
        shells: [2, 8, 16, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png",
       color: "#e9ff08"},
      {
        nombre: 'Cobre',
        masaAtomica: 63.5463,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 29,
        periodoo: 4,
        noOxidacion: "+1, +2",
        electronegatividad: 1.9,
        impactoEconomico: "Alto",
        impactoAmbiental: "Bajo",
        simbolo: 'Cu',
        xpos: 11,
        ypos: 4,
        shells: [2, 8, 18, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Zinc',
        masaAtomica: 65.382,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 30,
        periodoo: 4,
        noOxidacion: "+2",
        electronegatividad: 1.65,
        impactoEconomico: "Alto",
        impactoAmbiental: "Bajo",
        simbolo: 'Zn',
        xpos: 12,
        ypos: 4,
        shells: [2, 8, 18, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Galio',
        masaAtomica: 69.7231,
        categoria: 'Otro metal',
        numeroAtomico: 31,
        periodoo: 4,
        noOxidacion: "+3",
        electronegatividad: 1.81,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Medio",
        simbolo: 'Ga',
        xpos: 13,
        ypos: 4,
        shells: [2, 8, 18, 3],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Germanio',
        masaAtomica: 72.6308,
        categoria: 'Metaloides',
        numeroAtomico: 32,
        periodoo: 4,
        noOxidacion: "+2, +4",
        electronegatividad: 2.01,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Alto",
        phase: 'Solid',
        simbolo: 'Ge',
        xpos: 14,
        ypos: 4,
        shells: [2, 8, 18, 4],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#15864e"},
      {
        nombre: 'Arsénio',
        masaAtomica: 74.9215956,  
        categoria: 'Metaloides',
        numeroAtomico: 33,
        periodoo: 4,
        noOxidacion: "-3, +3, +5",
        electronegatividad: 2.18,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Alto",
        simbolo: 'As',
        xpos: 15,
        ypos: 4,
        shells: [2, 8, 18, 5],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#15864e"},
      {
        nombre: 'Selenio',
        categoria: 'Otros no metales',
        masaAtomica: 78.9718,
        numeroAtomico: 34,
        periodoo: 4,
        noOxidacion: "-2, +4, +6",
        electronegatividad: 2.55,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Alto",
        simbolo: 'Se',
        xpos: 16,
        ypos: 4,
        shells: [2, 8, 18, 6],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#148088"},
      {
        nombre: 'Bromo',
        masaAtomica: 79.904,
        categoria: 'Halogenos',
        density: 3.1028,
        numeroAtomico: 35,
        periodoo: 4,
        noOxidacion: "-1, +1, +3, +5, +7",
        electronegatividad: 2.96,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Medio",
        simbolo: 'Br',
        xpos: 17,
        ypos: 4,
        shells: [2, 8, 18, 7],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#39a576"},
      {
        nombre: 'Kriptón',
        masaAtomica: 83.7982,
        categoria: 'Gas noble',
        numeroAtomico: 36,
        periodoo: 4,
        noOxidacion: "0",
        electronegatividad: "Deconocido",
        impactoEconomico: "Desconocidas",
        impactoAmbiental: "Desconocidas",      
        simbolo: 'Kr',
        xpos: 18,
        ypos: 4,
        shells: [2, 8, 18, 8],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e40c9c"},
      {
        nombre: 'Rubidio',
        masaAtomica: 85.46783,
        categoria: 'Metales Alcalinos',
        numeroAtomico: 37,
        periodoo: 5,
        noOxidacion: "+1",
        electronegatividad: 0.82,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'Rb',
        xpos: 1,
        ypos: 5,
        shells: [2, 8, 18, 8, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png",
       color: "#eb5d0b"},
      {
        nombre: 'Estroncio',
        masaAtomica: 87.621,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 38,
        periodoo: 5,
        noOxidacion: "+2",
        electronegatividad: 0.95,
        impactoEconomico: "Medio",
        impactoAmbiental: "Medio",
        simbolo: 'Sr',
        xpos: 2,
        ypos: 5,
        shells: [2, 8, 18, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e2b00a"},
      {
        nombre: 'Itrio',
        masaAtomica: 88.905842,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 39,
        periodoo: 5,
        noOxidacion: "+3",
        electronegatividad: 1.22,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'Y',
        xpos: 3,
        ypos: 5,
        shells: [2, 8, 18, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Circonio',
        masaAtomica: 91.2242,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 40,
        periodoo: 5,
        noOxidacion: "+4",
        electronegatividad: 1.33,
        impactoEconomico: "Alto",
        impactoAmbiental: "Bajo",
        simbolo: 'Y',
        simbolo: 'Zr',
        xpos: 4,
        ypos: 5,
        shells: [2, 8, 18, 10, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Niobio',
        masaAtomica: 92.906372,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 41,
        periodoo: 5,
        noOxidacion: "+5",
        electronegatividad: 1.6,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'Y',
        simbolo: 'Nb',
        xpos: 5,
        ypos: 5,
        shells: [2, 8, 18, 12, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Molibdeno',
        masaAtomica: 95.951,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 42,
        periodoo: 5,
        noOxidacion: "+6",
        electronegatividad: 2.16,
        impactoEconomico: "Alto",
        impactoAmbiental: "Bajo",
        simbolo: 'Y',
        simbolo: 'Mo',
        xpos: 6,
        ypos: 5,
        shells: [2, 8, 18, 13, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Tecnicio',
        masaAtomica: 98,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 43,
        periodoo: 5,
        noOxidacion: "+7",
        electronegatividad: 1.9,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Tc',
        xpos: 7,
        ypos: 5,
        shells: [2, 8, 18, 13, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Rutenio',
        masaAtomica: 101.072,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 44,
        periodoo: 5,
        noOxidacion: "+2, +3, +4, +6, +7, +8",
        electronegatividad: 2.2,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Ru',
        xpos: 8,
        ypos: 5,
        shells: [2, 8, 18, 15, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Rodio',
        masaAtomica: 102.905502,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 45,
        periodoo: 5,
        noOxidacion: "+1, +2, +3, +4, +5, +6",
        electronegatividad: 2.28,
        impactoEconomico: "Alto",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Rh',
        xpos: 9,
        ypos: 5,
        shells: [2, 8, 18, 16, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Paladio',
        masaAtomica: 106.421,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 46,
        periodoo: 5,
        noOxidacion: "0, +1, +2, +3, +4",
        electronegatividad: 2.20,
        impactoEconomico: "Alto",
        impactoAmbiental: "Moderado",         
        simbolo: 'Y',
        simbolo: 'Pd',
        xpos: 10,
        ypos: 5,
        shells: [2, 8, 18, 18],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Plata',
        masaAtomica: 107.86822,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 47,
        periodoo: 5,
        noOxidacion: "+1, +2, +3",
        electronegatividad: 1.93,
        impactoEconomico: "Alto",
        impactoAmbiental: "Moderado",
        simbolo: 'Y',
        simbolo: 'Ag',
        xpos: 11,
        ypos: 5,
        shells: [2, 8, 18, 18, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Cadmio',
        masaAtomica: 112.4144,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 48,
        periodoo: 5,
        noOxidacion: "+1, +2",
        electronegatividad: 1.69,
        impactoEconomico: "Medio",
        impactoAmbiental: "Alto",
        simbolo: 'Y',
        simbolo: 'Cd',
        xpos: 12,
        ypos: 5,
        shells: [2, 8, 18, 18, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Indio',
        masaAtomica: 114.8181,
        categoria: 'Otro metal',
        numeroAtomico: 49,
        periodoo: 5,
        noOxidacion: "+1, +2, +3",
        electronegatividad: 1.78,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'In',
        xpos: 13,
        ypos: 5,
        shells: [2, 8, 18, 18, 3],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Estaño',
        masaAtomica: 118.7107,
        categoria: 'Otro metal',
        numeroAtomico: 50,
        periodoo: 5,
        noOxidacion: "-4, -2, -1, +1, +2, +3, +4",
        electronegatividad: 1.96,
        impactoEconomico: "Alto",
        impactoAmbiental: "Alto",
        simbolo: 'Y',
        simbolo: 'Sn',
        xpos: 14,
        ypos: 5,
        shells: [2, 8, 18, 18, 4],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Antimonio',
        masaAtomica: 121.7601,
        categoria: 'Metaloides',
        numeroAtomico: 51,
        periodoo: 5,
        noOxidacion: "-3, -2, -1, +1, +2, +3, +4, +5",
        electronegatividad: 2.05,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Alto",
        simbolo: 'Y',
        simbolo: 'Sb',
        xpos: 15,
        ypos: 5,
        shells: [2, 8, 18, 18, 5],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#15864e"},
      {
        nombre: 'Telurio',
        masaAtomica: 127.603,
        categoria: 'Metaloides',
        density: 6.24,
        numeroAtomico: 52,
        periodoo: 5,
        noOxidacion: "-2, +2, +4, +5, +6",
        electronegatividad: 2.1,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Te',
        xpos: 16,
        ypos: 5,
        shells: [2, 8, 18, 18, 6],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#15864e"},
      {
        nombre: 'Yodo',
        masaAtomica: 126.904473,
        categoria: 'Halogenos',
        numeroAtomico: 53,
        periodoo: 5,
        noOxidacion: "-1, +1, +3, +5, +7",
        electronegatividad: 2.66,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'I',
        xpos: 17,
        ypos: 5,
        shells: [2, 8, 18, 18, 7],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#39a576"},
      {
        nombre: 'Xenón',
        masaAtomica: 131.2936,
        categoria: 'Gas noble',
        numeroAtomico: 54,
        periodoo: 5,
        noOxidacion: "0, +2, +4, +6, +8",
        electronegatividad: 2.6,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        phase: 'Gas',    
        simbolo: 'Y',
        simbolo: 'Xe',
        xpos: 18,
        ypos: 5,
        shells: [2, 8, 18, 18, 8],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e40c9c"},
      {
        nombre: 'Cesio',
        masaAtomica: 132.905451966,
        categoria: 'Metales Alcalinos',
        numeroAtomico: 55,
        periodoo: 6,
        noOxidacion: "+1",
        electronegatividad: 0.79,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Moderado",
        simbolo: 'Y',
        simbolo: 'Cs',
        xpos: 1,
        ypos: 6,
        shells: [2, 8, 18, 18, 8, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#eb5d0b"},
      {
        nombre: 'Bario',
        masaAtomica: 137.3277,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 56,
        periodoo: 6,
        noOxidacion: "+2",
        electronegatividad: 0.89,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Moderado",
        simbolo: 'Y',
        simbolo: 'Ba',
        xpos: 2,
        ypos: 6,
        shells: [2, 8, 18, 18, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e2b00a"},
      {
        nombre: 'Lutecio',
        masaAtomica: 138.905477,
        categoria: 'Lantanoides',
        numeroAtomico: 57,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.1,
        impactoEconomico: "Moderado",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'La',
        xpos: 3,
        ypos: 9,
        shells: [2, 8, 18, 18, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Cerio',
        masaAtomica: 140.1161,
        categoria: 'Lantanoides',
        numeroAtomico: 58,
        periodoo: 6,
        noOxidacion: "+2, +3, +4",
        electronegatividad: 1.12,
        impactoEconomico: "Moderado",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Ce',
        xpos: 4,
        ypos: 9,
        shells: [2, 8, 18, 19, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Praseodimio',
        masaAtomica: 140.907662,
        categoria: 'Lantanoides',
        numeroAtomico: 59,
        periodoo: 6,
        noOxidacion: "+2, +3, +4",
        electronegatividad: 1.13,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Desconocido",
        simbolo: 'Pr',
        xpos: 5,
        ypos: 9,
        shells: [2, 8, 18, 21, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Neodimio',
        masaAtomica: 144.2423,
        categoria: 'Lantanoides',
        numeroAtomico: 60,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.14,
        impactoEconomico: "Moderado",
        impactoAmbiental: "Desconocido",
        simbolo: 'Nd',
        xpos: 6,
        ypos: 9,
        shells: [2, 8, 18, 22, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Prometio',
        masaAtomica: 145,
        categoria: 'Lantanoides',
        numeroAtomico: 61,
        periodoo: 6,
        noOxidacion: "+3",
        electronegatividad: 1.13,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Pm',
        xpos: 7,
        ypos: 9,
        shells: [2, 8, 18, 23, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Samario',
        masaAtomica: 150.362,
        categoria: 'Lantanoides',
        numeroAtomico: 62,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.17,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Sm',
        xpos: 8,
        ypos: 9,
        shells: [2, 8, 18, 24, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Europio',
        masaAtomica: 151.9641,
        categoria: 'Lantanoides',
        numeroAtomico: 63,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.2,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Eu',
        xpos: 9,
        ypos: 9,
        shells: [2, 8, 18, 25, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Gadolinium',
        masaAtomica: 157.253,
        categoria: 'Lantanoides',
        numeroAtomico: 64,
        periodoo: 6,
        noOxidacion: "+1, +2, +3",
        electronegatividad: 1.2,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Gd',
        xpos: 10,
        ypos: 9,
        shells: [2, 8, 18, 25, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Terbio',
        masaAtomica: 158.925352,
        categoria: 'Lantanoides',
        numeroAtomico: 65,
        periodoo: 6,
        noOxidacion: "+3, +4",
        electronegatividad: 1.2,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Tb',
        xpos: 11,
        ypos: 9,
        shells: [2, 8, 18, 27, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Disprosio',
        masaAtomica: 162.5001,
        categoria: 'Lantanoides',
        numeroAtomico: 66,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.22,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Dy',
        xpos: 12,
        ypos: 9,
        shells: [2, 8, 18, 28, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Holmio',
        masaAtomica: 164.930332,
        categoria: 'Lantanoides',
        numeroAtomico: 67,
        periodoo: 6,
        noOxidacion: "+3",
        electronegatividad: 1.23,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Ho',
        xpos: 13,
        ypos: 9,
        shells: [2, 8, 18, 29, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Erbio',
        masaAtomica: 167.2593,
        categoria: 'Lantanoides',
        numeroAtomico: 68,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.24,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Er',
        xpos: 14,
        ypos: 9,
        shells: [2, 8, 18, 30, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Tulio',
        masaAtomica: 168.934222,
        categoria: 'Lantanoides',
        numeroAtomico: 69,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.25,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Tm',
        xpos: 15,
        ypos: 9,
        shells: [2, 8, 18, 31, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Iterbio',
        masaAtomica: 173.0451,
        categoria: 'Lantanoides',
        numeroAtomico: 70,
        periodoo: 6,
        noOxidacion: "+2, +3",
        electronegatividad: 1.1,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Yb',
        xpos: 16,
        ypos: 9,
        shells: [2, 8, 18, 32, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Lutecio',
        masaAtomica: 174.96681,
        categoria: 'Lantanoides',
        numeroAtomico: 71,
        periodoo: 6,
        noOxidacion: "+3",
        electronegatividad: 1.27,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Lu',
        xpos: 17,
        ypos: 9,
        shells: [2, 8, 18, 32, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: ""},
      {
        nombre: 'Hafnio',
        masaAtomica: 178.492,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 72,
        periodoo: 6,
        noOxidacion: "+2, +3, +4",
        electronegatividad: 1.3,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Hf',
        xpos: 4,
        ypos: 6,
        shells: [2, 8, 18, 32, 10, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Tantalo',
        masaAtomica: 180.947882,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 73,
        periodoo: 6,
        noOxidacion: "+2, +3, +4, +5",
        electronegatividad: 1.5,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'Y',
        simbolo: 'Ta',
        xpos: 5,
        ypos: 6,
        shells: [2, 8, 18, 32, 11, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Wolframio',
        appearance: 'grayish white, lustrous',
        masaAtomica: 183.841,
        boil: 6203,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 74,
        periodoo: 6,
        noOxidacion: "+2, +3, +4, +5, +6",
        electronegatividad: 2.36,
        impactoEconomico: "Alto",
        impactoAmbiental: "Bajo",
        phase: 'Solid',
        ymbol: 'Y',
        simbolo: 'W',
        xpos: 6,
        ypos: 6,
        shells: [2, 8, 18, 32, 12, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Renio',
        masaAtomica: 186.2071,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 75,
        periodoo: 6,
        noOxidacion: "+2, +3, +4, +5, +6, +7",
        electronegatividad: 1.9,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",  
        simbolo: 'Re',
        xpos: 7,
        ypos: 6,
        shells: [2, 8, 18, 32, 13, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Osmio',
        masaAtomica: 190.233,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 76,
        periodoo: 6,
        noOxidacion: "+2, +3, +4, +5, +6, +7, +8",
        electronegatividad: 2.2,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'Os',
        xpos: 8,
        ypos: 6,
        shells: [2, 8, 18, 32, 14, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Iridio',
        masaAtomica: 192.2173,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 77,
        periodoo: 6,
        noOxidacion: "+2, +3, +4, +5, +6",
        electronegatividad: 2.2,
        impactoEconomico: "Medio",
        impactoAmbiental: "Bajo",
        simbolo: 'Ir',
        xpos: 9,
        ypos: 6,
        shells: [2, 8, 18, 32, 15, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Platino',
        masaAtomica: 195.0849,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 78,
        periodoo: 6,
        noOxidacion: "+2, +4",
        electronegatividad: 2.28,
        impactoEconomico: "Muy alto",
        impactoAmbiental: "Moderado",
        simbolo: 'Pt',
        xpos: 10,
        ypos: 6,
        shells: [2, 8, 18, 32, 17, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Oro',
        masaAtomica: 196.9665695,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 79,
        periodoo: 6,
        noOxidacion: "+1, +3",
        electronegatividad: 2.54,
        impactoEconomico: "Muy alto",
        impactoAmbiental: "Alto",
        simbolo: 'Au',
        xpos: 11,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Mercurio',
        masaAtomica: 200.5923,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 80,
        periodoo: 6,
        noOxidacion: "+1, +2",
        electronegatividad: 2.00,
        impactoEconomico: "Alto",
        impactoAmbiental: "Muy alto",
         simbolo: 'Hg',
        xpos: 12,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Talio',
        masaAtomica: 204.38,
        categoria: 'Otro metal',
        numeroAtomico: 81,
        periodoo: 6,
        noOxidacion: "+1, +3",
        electronegatividad: 1.62,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Moderado",
        simbolo: 'Tl',
        xpos: 13,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 3],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Plomo',
        masaAtomica: 207.21,
        categoria: 'Otro metal',
        numeroAtomico: 82,
        periodoo: 6,
        noOxidacion: "+2, +4",
        electronegatividad: 1.87,
        impactoEconomico: "Moderado",
        impactoAmbiental: "Alto",
        simbolo: 'Pb',
        xpos: 14,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 4],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Bismoto',
        masaAtomica: 208.980401,
        categoria: 'Otro metal',
        numeroAtomico: 83,
        periodoo: 6,
        noOxidacion: "+3, +5",
        electronegatividad: 2.02,
        impactoEconomico: "Bajo",
        impactoAmbiental: "Bajo",
        simbolo: 'Bi',
        xpos: 15,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 5],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Polonio',
        masaAtomica: 209,
        categoria: 'Otro metal',
        numeroAtomico: 84,
        periodoo: 6,
        noOxidacion: "+2, +4, +6",
        electronegatividad: 2.0,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Alto",
        simbolo: 'Po',
        xpos: 16,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 6],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#0960e4"},
      {
        nombre: 'Astato',
        masaAtomica: 210,
        categoria: 'Halogenos',
        numeroAtomico: 85,
        periodoo: 6,
        noOxidacion: "+1, +3, +5, +7",
        electronegatividad: 2.2,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Desconocido",
        simbolo: 'At',
        xpos: 17,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 7],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#39a576"},
      {
        nombre: 'Radón',
        masaAtomica: 222,
        categoria: 'Gas noble',
        numeroAtomico: 86,
        periodoo: 6,
        noOxidacion: "",
        electronegatividad: 2.2,
        impactoEconomico: "Desconocido",
        impactoAmbiental: "Alto",
        simbolo: 'Rn',
        xpos: 18,
        ypos: 6,
        shells: [2, 8, 18, 32, 18, 8],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e40c9c"},
      {
        nombre: 'Francio',
        masaAtomica: 223,
        categoria: 'Metales Alcalinos',
        periodo: 7,
        noOxidacion: '+1',
        electronegatividad: 0.7,
        impactoEconomico: 'No tiene aplicaciones comerciales significativas.',
        impactoAmbiental: 'Francio no tiene un impacto ambiental conocido.',
        simbolo: 'Fr',
        xpos: 1,
        ypos: 7,
        shells: [2, 8, 18, 32, 18, 8, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#eb5d0b"},
      {
        nombre: 'Radio',
        masaAtomica: 226,
        categoria: 'Metal Alcalinoterreo',
        numeroAtomico: 88,
        periodo: 7,
        noOxidacion: '+2',
        electronegatividad: 0.9,
        impactoEconomico: 'Se utiliza en algunos relojes atómicos y en radioterapia, pero es muy raro y costoso de producir.',
        impactoAmbiental: 'El radio es altamente radiactivo y puede ser peligroso para la salud y el medio ambiente si no se maneja adecuadamente.',
        simbolo: 'Ra',
        xpos: 2,
        ypos: 7,
        shells: [2, 8, 18, 32, 18, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e2b00a"},
      {
        nombre: 'Actinidos',
        masaAtomica: 227,
        categoria: 'Actinoides',
        numeroAtomico: 89,
        periodo: 7,
        noOxidacion: '+3',
        electronegatividad: 1.1,
        impactoEconomico: 'Se utiliza en algunas aplicaciones médicas y científicas, pero es muy raro y costoso de producir.',
        impactoAmbiental: 'El actinio es altamente radiactivo y puede ser peligroso para la salud y el medio ambiente si no se maneja adecuadamente.',
        simbolo: 'Ac',
        xpos: 3,
        ypos: 10,
        shells: [2, 8, 18, 32, 18, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Thorio',
        masaAtomica: 232.03774,
        categoria: 'Actinoides',   
        numeroAtomico: 90,
        periodo: 7,
        noOxidacion: '+4',
        electronegatividad: 1.3,
        impactoEconomico: 'Se utiliza como combustible en algunos reactores nucleares y en algunas aplicaciones médicas e industriales.',
        impactoAmbiental: 'El torio es ligeramente radiactivo y puede ser peligroso para la salud y el medio ambiente si no se maneja adecuadamente.',
        simbolo: 'Th',
        xpos: 4,
        ypos: 10,
        shells: [2, 8, 18, 32, 18, 10, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Protactinio',
        masaAtomica: 231.035882,
        categoria: 'Actinoides',
        numeroAtomico: 91,
        periodo: 7,
        noOxidacion: '+5',
        electronegatividad: 1.5,
        impactoEconomico: 'Se utiliza en algunas aplicaciones científicas y en reactores nucleares, pero es muy raro y costoso de producir.',
        impactoAmbiental: 'El protactinio es altamente radiactivo y puede ser peligroso para la salud y el medio ambiente si no se maneja adecuadamente.'
,      
       simbolo: 'Pa',
        xpos: 5,
        ypos: 10,
        shells: [2, 8, 18, 32, 20, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Uranio',
        masaAtomica: 238.028913,
        categoria: 'Actinoides',
        numeroAtomico: 92,
        periodo: 7,
        simbolo: 'U',
        xpos: 6,
        ypos: 10,
        shells: [2, 8, 18, 32, 21, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Neptunio',
        masaAtomica: 237,
        categoria: 'Actinoides',
        numeroAtomico: 93,
        periodo: 7,
        noOxidacion: "+3, +4, +5, +6, +7",
        electronegatividad: 1.36,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
        simbolo: 'Np',
        xpos: 7,
        ypos: 10,
        shells: [2, 8, 18, 32, 22, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Plutonio',
        masaAtomica: 244,
        categoria: 'Actinoides',
        numeroAtomico: 94,
        periodo: 7,
        noOxidacion: "+2, +3, +4, +5, +6, +7, +8",
        electronegatividad: 1.28,
        impactoEconomico: 'Alto',
        impactoAmbiental: 'Alto',
        simbolo: 'Pu',
        xpos: 8,
        ypos: 10,
        shells: [2, 8, 18, 32, 24, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Americio',
        masaAtomica: 243,
        categoria: 'Actinoides',
        numeroAtomico: 95,
        periodo: 7,
        noOxidacion: "+2, +3, +4, +5, +6",
        electronegatividad: 1.13,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
        simbolo: 'Am',
        xpos: 9,
        ypos: 10,
        shells: [2, 8, 18, 32, 25, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Curio',
        masaAtomica: 247,
        boil: 3383,
        categoria: 'Actinoides',
        numeroAtomico: 96,
        periodo: 7,
        noOxidacion: "+2, +3, +4, +5, +6",
        electronegatividad: 1.28,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
       simbolo: 'Cm',
        xpos: 10,
        ypos: 10,
        shells: [2, 8, 18, 32, 25, 9, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Berkelio',
        masaAtomica: 247,
        categoria: 'Actinoides',
        numeroAtomico: 97,
        periodo: 7,
        noOxidacion: "+3, +4, +5, +6",
        electronegatividad: 1.3,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
        simbolo: 'Bk',
        xpos: 11,
        ypos: 10,
        shells: [2, 8, 18, 32, 27, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Californio',
        masaAtomica: 251,
        categoria: 'Actinoides',
        numeroAtomico: 98,
        periodo: 7,
        noOxidacion: "+2, +3, +4, +5, +6",
        electronegatividad: 1.3,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
        simbolo: 'Cf',
        xpos: 12,
        ypos: 10,
        shells: [2, 8, 18, 32, 28, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Einstinio',
        masaAtomica: 252,
        categoria: 'Actinoides',
        numeroAtomico: 99,
        periodo: 7,
        noOxidacion: "+2, +3, +4, +5, +6, +7",
        electronegatividad: 1.3,
        impactoEconomico: 'Desconocido',
        impactoAmbiental: 'Desconocido',
        simbolo: 'Es',
        xpos: 13,
        ypos: 10,
        shells: [2, 8, 18, 32, 29, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Fermio',
        masaAtomica: 257,
        categoria: 'Actinoides',
        numeroAtomico: 100,
        periodo: 7,
        simbolo: 'Fm',
        xpos: 14,
        ypos: 10,
        shells: [2, 8, 18, 32, 30, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Mendelevio',
        masaAtomica: 258,
        categoria: 'Actinoides',
        numeroAtomico: 101,
        periodo: 7,
        simbolo: 'Md',
        xpos: 15,
        ypos: 10,
        shells: [2, 8, 18, 32, 31, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Nobelio',
        masaAtomica: 259,
        categoria: 'Actinoides',
        numeroAtomico: 102,
        periodo: 7,
        simbolo: 'No',
        xpos: 16,
        ypos: 10,
        shells: [2, 8, 18, 32, 32, 8, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Lawrencio',
        masaAtomica: 266,
        categoria: 'Actinoides',
        numeroAtomico: 103,
        periodo: 7,
        simbolo: 'Lr',
        xpos: 17,
        ypos: 10,
        shells: [2, 8, 18, 32, 32, 8, 3],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#ad1deb"},
      {
        nombre: 'Rutherfordio',
        masaAtomica: 267,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 104,
        periodo: 7,
        simbolo: 'Rf',
        xpos: 4,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 10, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Dubnio',
        masaAtomica: 268,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 105,
        periodo: 7,
        simbolo: 'Db',
        xpos: 5,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 11, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Seaborgio',
        masaAtomica: 269,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 106,
        periodo: 7,
        simbolo: 'Sg',
        xpos: 6,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 12, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Bohrio',
        masaAtomica: 270,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 107,
        periodo: 7,
        simbolo: 'Bh',
        xpos: 7,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 13, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Hasio',
        masaAtomica: 269,
        categoria: 'Metales alcalinoterreos',
        numeroAtomico: 108,
        periodo: 7,
        simbolo: 'Hs',
        xpos: 8,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 14, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "#e9ff08"},
      {
        nombre: 'Meithnerio',
        masaAtomica: 278,
        categoria: 'Desconocido',
        numeroAtomico: 109,
        periodo: 7,
        simbolo: 'Mt',
        xpos: 9,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 15, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Darmstatio',
        masaAtomica: 281,
        categoria: 'Desconocido',
        numeroAtomico: 110,
        periodo: 7,
        simbolo: 'Ds',
        xpos: 10,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 16, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Roentgenio',
        masaAtomica: 282,
        categoria: 'Desconocido',
        numeroAtomico: 111,
        periodo: 7,
        simbolo: 'Rg',
        xpos: 11,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 17, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Copernicio',
        boil: 3570,
        categoria: 'Desconocido',
        numeroAtomico: 112,
        periodo: 7,
        simbolo: 'Cn',
        xpos: 12,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 2],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Nihonio',
        masaAtomica: 286,
        categoria: 'Desconocido',
        numeroAtomico: 113,
        periodo: 7,
        simbolo: 'Nh',
        xpos: 13,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 3],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Flerovio',
        masaAtomica: 289,
        categoria: 'Desconocido',
        numeroAtomico: 114,
        periodo: 7,
        simbolo: 'Fl',
        xpos: 14,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 4],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Moscovio',
        masaAtomica: 289,
        categoria: 'Desconocido',
        numeroAtomico: 115,
        periodo: 7,
        simbolo: 'Mc',
        xpos: 15,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 5],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Livermorio',
        masaAtomica: 293,
        categoria: 'Desconocido',
        numeroAtomico: 116,
        periodo: 7,
        simbolo: 'Lv',
        xpos: 16,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 6],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Teneso',
        masaAtomica: 294,
        categoria: 'Desconocido',
        numeroAtomico: 117,
        periodo: 7,
        simbolo: 'Ts',
        xpos: 17,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 7],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Oganesón',
        masaAtomica: 294,
        categoria: 'Desconocido',
        numeroAtomico: 118,
        periodo: 7,
        simbolo: 'Og',
        xpos: 18,
        ypos: 7,
        shells: [2, 8, 18, 32, 32, 18, 8],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png"
      , color: "rgb(0, 255, 255)"},
      {
        nombre: 'Ununennium',
        masaAtomica: 315,
        categoria: 'Desconocido',     
        density: 3,
        numeroAtomico: 119,
        periodo: 8,      
        simbolo: 'Uue',
        xpos: 1,
        ypos: 8,
        shells: [2, 8, 18, 32, 32, 18, 8, 1],
         urlNatural: "/images/natural/.png",
           urlUtilidad: "/images/utilidad/.png",
        color: "rgb(0, 255, 255)"
      }
    ]
  };
   
